export enum FeaturesEnum {
    Dashboard = 1,
    History = 2,
    HistoryDonations = 3,
    HistoryWithdrawals = 4,
    HistoryDealsResult = 5,
    Donors = 6,
    DonorsPendingDonations = 7,
    DonorsPlatinum = 8,
    DonorsGold = 9,
    DonorsSilver = 10,
    Withdrawals = 11,
    SilverDashboard = 12,
    SilverHistory = 13,
    Mechanics = 14,
    SilverDonate = 15,
    SilverNotification = 16,
    ContactUs = 17,
    Profile = 18,
    GameSettings = 19,
}